# Generated by Django 2.0.2 on 2018-03-08 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Enter a brief description of the event', max_length=1000)),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='Enter the starting date and time of your event')),
                ('end_time', models.DateTimeField(auto_now_add=True, help_text='Enter the ending date and time of your event')),
                ('picture', models.ImageField(default='imgs/None/no-img.jpg', upload_to='imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your event location (e.g. Umass, Mount Holyoke College).', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(help_text='Popularity of the event')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField(help_text='Enter your event price (e.g. 0, 5.5, 10).')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your event tag (e.g. cultural, sport).', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(default='imgs/None/no-img.jpg', upload_to='imgs/')),
                ('contact', models.CharField(help_text='Enter your email address or phone number.', max_length=100)),
                ('bio', models.TextField(help_text='Enter a brief description of you/your organization.', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_Vent.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='popularity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_Vent.Popularity'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_Vent.Price'),
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(help_text='Select a tag for this book', to='e_Vent.Tag'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_Vent.User'),
        ),
    ]
