# Generated by Django 2.0.2 on 2018-03-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_Vent', '0002_auto_20180315_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(help_text='Enter the ending date and time of your event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(help_text='Enter the starting date and time of your event'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.PositiveIntegerField(default=0, help_text='Enter your event price (e.g. 0, 5, 10).'),
        ),
    ]
