# Generated by Django 2.0.2 on 2018-03-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_Vent', '0003_auto_20180318_1713'),
        ('e_Vent', '0003_auto_20180319_1152'),
    ]

    operations = [
    ]
