# Generated by Django 2.0.2 on 2018-03-26 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_Vent', '0004_merge_20180319_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_Vent.Price'),
        ),
    ]
