# Generated by Django 2.0.2 on 2018-03-27 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_Vent', '0006_auto_20180327_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='popularity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_Vent.Popularity'),
        ),
    ]
