# Generated by Django 2.0.2 on 2018-03-28 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_Vent', '0007_auto_20180327_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularity',
            name='name',
            field=models.ForeignKey(default=0, help_text='Popularity of the event', on_delete=django.db.models.deletion.CASCADE, to='e_Vent.Popularity'),
        ),
    ]
