# Generated by Django 2.0.2 on 2018-03-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_Vent', '0009_auto_20180328_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='href',
            field=models.URLField(default=0, help_text='Input a link for this event'),
            preserve_default=False,
        ),
    ]
