# Generated by Django 2.0.2 on 2018-03-29 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_Vent', '0012_auto_20180328_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='href',
        ),
    ]
