# Generated by Django 2.0.2 on 2018-03-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_Vent', '0013_remove_event_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='href',
            field=models.URLField(default='https://www.google.com/', help_text='Input a link for this event'),
        ),
    ]
