# Generated by Django 2.0.2 on 2018-04-09 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_Vent', '0014_event_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='event',
            field=models.ManyToManyField(related_name='_user_event_+', to='e_Vent.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='e_Vent.User'),
        ),
    ]
