# Generated by Django 2.0.2 on 2018-04-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_Vent', '0017_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='postsaves', to='e_Vent.Profile'),
        ),
    ]
