# Generated by Django 2.0.2 on 2018-04-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_Vent', '0021_auto_20180415_1943'),
        ('e_Vent', '0021_auto_20180415_1521'),
    ]

    operations = [
    ]
