# Generated by Django 2.0.2 on 2018-04-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_Vent', '0022_merge_20180417_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(help_text='Example: 2017-03-07 06:00:00', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(help_text='Example: 2017-03-07 06:00:00', verbose_name='Start Time'),
        ),
    ]
